version: "3.8"
services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: postgres_password
        ports:
            - 5432:5432
        networks:
            - microservices

    client:
        build:
            context: .
            dockerfile: cars_info_client/Dockerfile
        environment:
            HOST: server
        image: client
        networks:
            - microservices

    server:
        build:
            context: .
            dockerfile: cars_info_server/Dockerfile
        environment:
            HOST: server
            DB_HOST: 'db'
            DB_PORT: 5432
            DB_NAME: "postgres"
            DB_PASSWORD: "postgres_password"
        image: server
#

        networks:
            - microservices



networks:
    microservices: