# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import cars_info_pb2 as cars__info__pb2


class InfoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInfoForModel = channel.unary_unary(
                '/Info/GetInfoForModel',
                request_serializer=cars__info__pb2.RequestForOneModel.SerializeToString,
                response_deserializer=cars__info__pb2.ResponseForOneModel.FromString,
                )
        self.GetInfoForBrand = channel.unary_stream(
                '/Info/GetInfoForBrand',
                request_serializer=cars__info__pb2.RequestForBrand.SerializeToString,
                response_deserializer=cars__info__pb2.ResponseInfoForBrand.FromString,
                )


class InfoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetInfoForModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInfoForBrand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InfoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInfoForModel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInfoForModel,
                    request_deserializer=cars__info__pb2.RequestForOneModel.FromString,
                    response_serializer=cars__info__pb2.ResponseForOneModel.SerializeToString,
            ),
            'GetInfoForBrand': grpc.unary_stream_rpc_method_handler(
                    servicer.GetInfoForBrand,
                    request_deserializer=cars__info__pb2.RequestForBrand.FromString,
                    response_serializer=cars__info__pb2.ResponseInfoForBrand.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Info', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Info(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetInfoForModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Info/GetInfoForModel',
            cars__info__pb2.RequestForOneModel.SerializeToString,
            cars__info__pb2.ResponseForOneModel.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetInfoForBrand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Info/GetInfoForBrand',
            cars__info__pb2.RequestForBrand.SerializeToString,
            cars__info__pb2.ResponseInfoForBrand.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
